# Fetches the Supabase API keys via the CLI and writes them to .env.
#
# Run this yourself -- it handles the service_role key, which bypasses row
# level security and should not pass through anyone else's hands.
#
#   powershell -ExecutionPolicy Bypass -File scripts\write-env.ps1
#
# Writes to the project root regardless of where you run it from.

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$ref = "qigiwthmigmwpbabznge"

# 2>$null matters: the CLI prints an upgrade notice to stderr, and without
# this PowerShell folds it into the pipeline and ConvertFrom-Json chokes.
$raw = & supabase projects api-keys --project-ref $ref --output json 2>$null

if (-not $raw) {
    throw "The Supabase CLI returned nothing. Are you logged in? Try: supabase login"
}

try {
    $keys = $raw | ConvertFrom-Json
} catch {
    throw "Could not parse the CLI output as JSON. Raw output started with: $($raw | Select-Object -First 1)"
}

$anon = ($keys | Where-Object { $_.name -eq 'anon' }).api_key
$svc = ($keys | Where-Object { $_.name -eq 'service_role' }).api_key

# Newer projects may use the publishable/secret naming instead.
if (-not $anon) { $anon = ($keys | Where-Object { $_.name -like '*publishable*' }).api_key }
if (-not $svc) { $svc = ($keys | Where-Object { $_.name -like '*secret*' }).api_key }

if (-not $anon -or -not $svc) {
    $seen = ($keys | ForEach-Object { $_.name }) -join ', '
    throw "Could not find both keys. Key names returned: $seen"
}

$path = Join-Path $root ".env"
Set-Content -Path $path -Encoding utf8 -Value @(
    "# Generated by scripts/write-env.ps1. Never commit this file.",
    "SUPABASE_URL=https://$ref.supabase.co",
    "SUPABASE_PROJECT_REF=$ref",
    "SUPABASE_ANON_KEY=$anon",
    "SUPABASE_SERVICE_ROLE_KEY=$svc"
)

Write-Host "wrote $path"
Write-Host ("  anon key          {0} chars" -f $anon.Length)
Write-Host ("  service_role key  {0} chars" -f $svc.Length)
Write-Host ""
Write-Host "Verify with:  python -m prescore env"
