// Public, safe to ship: this is the anon key, meant for browser use.
// Row Level Security enforces what it can read/write, not secrecy of
// this string -- see supabase/migrations/ for the RLS policies.
// Regenerated by `prescore export` -- do not hand-edit.
window.PRESCORE_CONFIG = {
  supabaseUrl: "https://qigiwthmigmwpbabznge.supabase.co",
  anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZ2l3dGhtaWdtd3BiYWJ6bmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0OTA2ODIsImV4cCI6MjEwMjA2NjY4Mn0.gZSrndzftPvZIdAHkhZWNNgdCE4ZAnrxJ11DggAAcYE",
  modelVersion: "poisson-dc-1.3",
  league: "EPL",
};
